ALTER TABLE webapps_rating_descriptors
    DROP COLUMN `has_esrb_alcohol`,
    ADD COLUMN `has_esrb_alcohol_ref` bool NOT NULL,

    ADD COLUMN `has_generic_tobacco_ref` bool NOT NULL,
    ADD COLUMN `has_generic_alcohol_use` bool NOT NULL,
    ADD COLUMN `has_generic_drug_use` bool NOT NULL,
    ADD COLUMN `has_generic_tobacco_use` bool NOT NULL,
    ADD COLUMN `has_generic_violence` bool NOT NULL,
    ADD COLUMN `has_generic_violence_ref` bool NOT NULL,
    ADD COLUMN `has_generic_no_descs` bool NOT NULL,
    ADD COLUMN `has_generic_comic_mischief` bool NOT NULL,
    ADD COLUMN `has_generic_alcohol_tobacco_ref` bool NOT NULL,
    ADD COLUMN `has_generic_drug_alcohol_ref` bool NOT NULL,
    ADD COLUMN `has_generic_alcohol_tobacco_use` bool NOT NULL,
    ADD COLUMN `has_generic_drug_alcohol_use` bool NOT NULL,
    ADD COLUMN `has_generic_drug_tobacco_ref` bool NOT NULL,
    ADD COLUMN `has_generic_drug_alcohol_tobacco_ref` bool NOT NULL,
    ADD COLUMN `has_generic_drug_tobacco_use` bool NOT NULL,
    ADD COLUMN `has_generic_drug_alcohol_tobacco_use` bool NOT NULL,
    ADD COLUMN `has_generic_scary` bool NOT NULL,
    ADD COLUMN `has_generic_hate_speech` bool NOT NULL,
    ADD COLUMN `has_generic_crime` bool NOT NULL,
    ADD COLUMN `has_generic_crime_instruct` bool NOT NULL;
